const songs = [
  {
    id: 0,
    title: "Waiting For You",
    artist: "MONO, Onionn",
    avatar: "./assets/images/WaitingForYou.jpg",
    mp3: "./assets/music/WaitingForYou.mp3",
  },
  {
    id: 1,
    title: "Em Là",
    artist: "MONO, Onionn",
    avatar: "./assets/images/WaitingForYou.jpg",
    mp3: "./assets/music/EmLa.mp3",
  },
  {
    id: 2,
    title: "Cơn Mưa Ngang Qua",
    artist: "Sơn Tùng MTP",
    avatar: "./assets/images/ConMuaNgangQua.jpg",
    mp3: "./assets/music/ConMuaNgangQua.mp3",
  },
  {
    id: 3,
    title: "Nắng Ấm Xa Dần",
    artist: "Sơn Tùng MTP",
    avatar: "./assets/images/nangamxadan.jpg",
    mp3: "./assets/music/NangAmXaDan.mp3",
  },
  {
    id: 4,
    title: "Khuôn Mặt Đáng Thương",
    artist: "Sơn Tùng MTP",
    avatar: "./assets/images/MTP.jpg",
    mp3: "./assets/music/KhuonMatDangThuongOrigin.mp3",
  },
  {
    id: 5,
    title: "Chúng Ta Không Thuộc Về Nhau",
    artist: "Sơn Tùng MTP",
    avatar: "./assets/images/ChungTaKhongThuocVeNhau.jpg",
    mp3: "./assets/music/ChungTaKhongThuocVeNhau.mp3",
  },
  {
    id: 6,
    title: "Remember Me",
    artist: "Sơn Tùng MTP",
    avatar: "./assets/images/RememberMe.jpg",
    mp3: "./assets/music/RememberMe.mp3",
  },
  {
    id: 7,
    title: "RememberMe",
    artist: "Sơn Tùng MTP",
    avatar: "./assets/images/ChayNgayDi.png",
    mp3: "./assets/music/ChayNgayDi.mp3",
  },
  {
    id: 8,
    title: "Lạc Trôi",
    artist: "Sơn Tùng MTP",
    avatar: "./assets/images/LacTroi.jpg",
    mp3: "./assets/music/LacTroi.mp3",
  },
  {
    id: 9,
    title: "Hãy Trao Cho Anh",
    artist: "Sơn Tùng MTP, SnoopDogg",
    avatar: "./assets/images/HayTraoChoAnh.jpg",
    mp3: "./assets/music/HayTraoChoAnh.mp3",
  },
  {
    id: 10,
    title: "Sky Decade - Intro 2022",
    artist: "Sơn Tùng MTP",
    avatar: "./assets/images/SkyDecade.jpg",
    mp3: "./assets/music/Intro2022-SkyDecade.mp3",
  },
  {
    id: 11,
    title: "Cơn Mưa Xa Dần",
    artist: "Sơn Tùng MTP",
    avatar: "./assets/images/SkyDecade.jpg",
    mp3: "./assets/music/ConMuaXaDan.mp3",
  },
  {
    id: 12,
    title: "Nắng Ấm Ngang Qua",
    artist: "Sơn Tùng MTP",
    avatar: "./assets/images/SkyDecade.jpg",
    mp3: "./assets/music/NangAmNgangQua.mp3",
  },

  {
    id: 13,
    title: "vaicaunoicokhiennguoithaydoi",
    artist: "GREY D, tlinh",
    avatar: "./assets/images/vaicaunoicokhiennguoithaydoi.jpg",
    mp3: "./assets/music/vaicaunoicokhiennguoithaydoi.mp3",
  },
  {
    id: 14,
    title: "sài gòn hôm nay mưa",
    artist: "JSOL, Hoàng Duyên",
    avatar: "./assets/images/saigonhomnaymua.jpg",
    mp3: "./assets/music/SaiGonHomNayMua.mp3",
  },
  {
    id: 15,
    title: "mama boy",
    artist: "amee",
    avatar: " ./assets/images/01.jpg",
    mp3: "./assets/music/01.mp3",
  },
  {
    id: 16,
    title: "Xích Thêm Chút Nữa",
    artist: "GREY D, tlinh",
    avatar: "./assets/images/xichthemchutnua.jpg",
    mp3: "./assets/music/xichthemchutnua.mp3",
  },
  {
    id: 17,
    title: "vì mẹ anh bắt chia tay",
    artist: "miu lê, karik",
    avatar: "./assets/images/02.jpg",
    mp3: "./assets/music/02.mp3",
  },
  {
    id: 18,
    title: "Tháng Năm",
    artist: "Soobin Hoàng Sơn, SlimV",
    avatar: "./assets/images/thangnam.jpg",
    mp3: "./assets/music/ThangNam.mp3",
  },
  {
    id: 19,
    title: "Xin Đừng Nhấc Máy",
    artist: "Han Sara, T.R.I",
    avatar: "./assets/images/xindungnhacmay.jpg",
    mp3: "./assets/music/XinDungNhacMay.mp3",
  },
  {
    id: 20,
    title: "matchanah",
    artist: "híu, bâu",
    avatar: "./assets/images/07.jpg",
    mp3: "./assets/music/07.mp3",
  },
  {
    id: 21,
    title: "QUERRY ",
    artist: "QNT, TRUNG TRẦN, RPT MCK",
    avatar: "./assets/images/05.jpg",
    mp3: "./assets/music/05.mp3",
  },
  {
    id: 22,
    title: "lời đường mật",
    artist: "lyly, hiếu thứ hai",
    avatar: "./assets/images/08.jpg",
    mp3: "./assets/music/08.mp3",
  },
  {
    id: 23,
    title: "cô gái vàng",
    artist: "huyr, tùng viu",
    avatar: "./assets/images/09.jpg",
    mp3: "./assets/music/09.mp3",
  },
  {
    id: 24,
    title: "cho mình em",
    artist: "đen, binz",
    avatar: "./assets/images/10.jpg",
    mp3: "./assets/music/10.mp3",
  },
  {
    id: 25,
    title: "Shay Nắnggg",
    artist: "amme, obito",
    avatar: "./assets/images/03.jpg",
    mp3: "./assets/music/03.mp3",
  },
  {
    id: 26,
    title: "chạy khỏi thế giới này",
    artist: "Da LAB, Phương Ly",
    avatar: "./assets/images/04.jpg",
    mp3: "./assets/music/04.mp3",
  },
  {
    id: 27,
    title: "gác lại âu lo",
    artist: "dalab, miu lê",
    avatar: "./assets/images/06.jpg",
    mp3: "./assets/music/06.mp3",
  },
];

export default songs;
